version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MARIADB_DATABASE: app_db
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app123
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:

